app/config/routes.rb
Rails.application.routes.draw do
  resources :logins
  resources :orders
  resources :salaries
  resources :people
  resources :companies
  resources :educations
  resources :mysites
  resources :sign_ups
  resources :registrations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/app/models/company.rb
class Company < ApplicationRecord
    validates :size, inclusion: {in: %w(small medium large), message: "%{value} is not a valid size"}
end

app/app/models/education.rb
class Education < ApplicationRecord
    validates :qualification, format: {with: /\A[a-zA-Z]+\z/ , message: "Only letters allowed"}
end

app/app/models/login.rb
class Login < ApplicationRecord
    validates :username, uniqueness: true
end

app/app/models/mysite.rb
class Mysite < ApplicationRecord
    validates :website, exclusion: {in: %w(www.google.ie), message: "Subdomain %{value} is not permitted."}
end

app/app/models/order.rb
class Order < ApplicationRecord
    validates :item, :price, presence: true
end

app/app/models/person.rb
class Person < ApplicationRecord
    validates :name, length: {minimum: 2}
    validates :bio, length: {maximum: 500}
    validates :password, length: {in: 6..20}
    validates :registration_number, length: {is: 6}
end

app/app/models/registration.rb
class Registration < ApplicationRecord
    validates :acceptpolicy, acceptance: {:accept => true}
end

app/app/models/salary.rb
class Salary < ApplicationRecord
    #validates :wage, numericality: true
    validates :wage, numericality: {only_integer: true}
end

app/app/models/sign_up.rb
class SignUp < ApplicationRecord
    validates :password, confirmation: true
end

app/app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:username, :password)
    end
end

app/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:item, :price)
    end
end

app/app/controllers/sign_ups_controller.rb
class SignUpsController < ApplicationController
  before_action :set_sign_up, only: [:show, :edit, :update, :destroy]

  # GET /sign_ups
  # GET /sign_ups.json
  def index
    @sign_ups = SignUp.all
  end

  # GET /sign_ups/1
  # GET /sign_ups/1.json
  def show
  end

  # GET /sign_ups/new
  def new
    @sign_up = SignUp.new
  end

  # GET /sign_ups/1/edit
  def edit
  end

  # POST /sign_ups
  # POST /sign_ups.json
  def create
    @sign_up = SignUp.new(sign_up_params)

    respond_to do |format|
      if @sign_up.save
        format.html { redirect_to @sign_up, notice: 'Sign up was successfully created.' }
        format.json { render :show, status: :created, location: @sign_up }
      else
        format.html { render :new }
        format.json { render json: @sign_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sign_ups/1
  # PATCH/PUT /sign_ups/1.json
  def update
    respond_to do |format|
      if @sign_up.update(sign_up_params)
        format.html { redirect_to @sign_up, notice: 'Sign up was successfully updated.' }
        format.json { render :show, status: :ok, location: @sign_up }
      else
        format.html { render :edit }
        format.json { render json: @sign_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sign_ups/1
  # DELETE /sign_ups/1.json
  def destroy
    @sign_up.destroy
    respond_to do |format|
      format.html { redirect_to sign_ups_url, notice: 'Sign up was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sign_up
      @sign_up = SignUp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sign_up_params
      params.require(:sign_up).permit(:username, :password, :password_confirmation)
    end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/companies_helper.rb
module CompaniesHelper
end

app/app/helpers/educations_helper.rb
module EducationsHelper
end

app/app/helpers/logins_helper.rb
module LoginsHelper
end

app/app/helpers/mysites_helper.rb
module MysitesHelper
end

app/app/helpers/orders_helper.rb
module OrdersHelper
end

app/app/helpers/people_helper.rb
module PeopleHelper
end

app/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/app/helpers/salaries_helper.rb
module SalariesHelper
end

app/app/helpers/sign_ups_helper.rb
module SignUpsHelper
end

app/app/views/sign_ups/_form.html.erb
<%= form_with(model: sign_up, local: true) do |form| %>
  <% if sign_up.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sign_up.errors.count, "error") %> prohibited this sign_up from being saved:</h2>

      <ul>
      <% sign_up.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :sign_up_username %>
  </div>

  <div class="field">
    <%= form.label :password %><br />
    <%= password_field :sign_up, :password %><br />
    <%= password_field :sign_up, :password_confirmation%>
    <!--<- form.text_field :password, id: :sign_up_password %> -->
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/app/views/sign_ups/edit.html.erb
<h1>Editing Sign Up</h1>

<%= render 'form', sign_up: @sign_up %>

<%= link_to 'Show', @sign_up %> |
<%= link_to 'Back', sign_ups_path %>

app/app/views/sign_ups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sign Ups</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sign_ups.each do |sign_up| %>
      <tr>
        <td><%= sign_up.username %></td>
        <td><%= sign_up.password %></td>
        <td><%= link_to 'Show', sign_up %></td>
        <td><%= link_to 'Edit', edit_sign_up_path(sign_up) %></td>
        <td><%= link_to 'Destroy', sign_up, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sign Up', new_sign_up_path %>

app/app/views/sign_ups/new.html.erb
<h1>New Sign Up</h1>

<%= render 'form', sign_up: @sign_up %>

<%= link_to 'Back', sign_ups_path %>

app/app/views/sign_ups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @sign_up.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @sign_up.password %>
</p>

<%= link_to 'Edit', edit_sign_up_path(@sign_up) %> |
<%= link_to 'Back', sign_ups_path %>